### ISSUE TITLE
[Android Bootcamp] Project 1: Instagram popular photos

### ISSUE THREAD

**Issue by varungu** [varungu/Android-Bootcamp#2]
My app is complete, Please review. /cc @codepathreview @codepath
README.html had been added with details.

Completed user stories:

·         Required: Graphic, Caption, Username, user profile image
·         Optional: relative timestamp
·         Advanced: Add pull-to-refresh for popular stream with SwipeRefreshLayout
·         Advanced: Display each photo with the same style and proportions as the real Instagram (see screens below)
·         Advanced: Display each user profile image using a RoundedImageView
·         Advanced: Display a nice default placeholder graphic for each image during loading (read more about Picasso)
·         Extra: Add infinite scroll

**Comment by nesquena** [comment]
You finished this rather fast, and your commit history shows you must have started this ahead of time? Not a problem, just curious.

**Comment by varungu** [comment]
@nesquena 

I watched video and created basic app (ugly looking one) ahead of time. Spent few hours today to do other stories. 

Goal is to do all stories every week. I know it will be difficult, so using my time on it whenever I can.

**Comment by nesquena** [comment]
Glad to hear that, sounds like a great approach for the course.

**Comment by varungu** [comment]
Please review. /cc @codepathreview @codepath
Added videoview since last time. Updated readme.html and walkthrough with the same.

Question: I noticed that my mainActivity refreshes on back from videoActivity. How can I make sure that it does not refresh and users return at at same location from where they started videoActivity?

**Comment by nesquena** [comment]
In the future, it would be best if you can submit your project once to us closer to the due date of the assignment. Of course feel free to push to github frequently and commit all the time. Just cc us once so it's easier to keep track. Also, we have many TAs who want to help out with questions so if you can email questions to support@codepath.com or to the google group, easier for people to respond. 

> I noticed that my mainActivity refreshes on back from videoActivity. How can I make sure that it does not refresh and users return at at same location from where they started videoActivity?

I can't see in your code where you are launching the videoview or how you are returning so it's difficult to answer this. The short of it is if you launch and dismiss the activity correctly, the user will be returned to the same location automatically. If you can share the specific code snippets, I can point out the issue. We will be discussing in detail next week as well.

**Comment by varungu** [comment]
@nesquena 

Sure Nathan. 

The code to launch activity is in InstagramPhotoAdapter
    ivPhoto.setImageResource(0);
        Picasso.with(getContext()).load(photo.imageUrl).placeholder(R.drawable.loader).into(ivPhoto);

```
    if (photo.type.equals("image")){
        ivPhoto.setOnClickListener(null);
    }
    else {
        ivPhoto.setOnClickListener(new View.OnClickListener() {
            public void onClick(View arg0) {

                // Start NewActivity.class
                Intent videoIntent = new Intent(getContext(), VideoViewActivity.class);
                videoIntent.putExtra("url", photo.videoUrl);
                videoIntent.putExtra("caption", photo.caption);
                getContext().startActivity(videoIntent);
            }
        });
    }
```

To dismiss activity, I am using back button in the actionBar (Top Bar). I am setting PhotoActivity as the parent of VideoViewActivity in manifest.

![image](https://cloud.githubusercontent.com/assets/2263278/7503755/d688e3ac-f3f9-11e4-9a6a-35dd1b391df7.png)

**Comment by nesquena** [comment]
Using `android:parentActivityName` to [declare the logical parent activity](http://developer.android.com/training/implementing-navigation/temporal.html#SynthesizeBackStack) of the detail activity enables a "back button" in the ActionBar but by default creates a new instance of the parent activity in the task stack. See [this stackoverflow post](http://stackoverflow.com/questions/12276027/how-can-i-return-to-a-parent-activity-correctly) to fix this by [adjusting the launch mode](http://guides.codepath.com/android/Navigation-and-Task-Stacks#launch-modes) of the activity.

**Comment by varungu** [comment]
Thanks for a quick response.

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:
- Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
- Correctly externalized string resources to strings.xml
- Nice to see you used the SwipeRefreshLayout for easy stream refreshes
- Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files) including package for activity.
- Good job using the [ViewHolder pattern](https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) to improve performance of photos `ListView`.
- Consider including a check to see if internet is available to detect any network failures. Show an appropriate message in case of failure.
- Consider overriding `onFailure` method in `JsonHttpResponseHandler` to handle error messages and notify user appropriately.

One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I would encourage you to complete the projects each week with required stories early and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) which covers the most common points we see for this project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this first project has given you a better sense of working with RelativeLayout which is a very flexible layout system, probably one of the most powerful responsive-first layout systems available across web and mobile platforms. This assignment also gave us our first introduction to networking, working with APIs and loading remote images. The next assignment will introduce new concept such as accepting user input and navigating between activities but will also reinforce important concepts such as networking, using APIs, handling remote images.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or or email us support@codepath.com.

**P.S.** Good to see you properly added the readme with features and screenshots to your project as described in the [submitting assignments](http://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments) guide!
