### ISSUE TITLE
[Android Bootcamp] Project 2: Google Image Search

### ISSUE THREAD

**Issue by varungu** [varungu/Android-Bootcamp#4]
My app is complete, Please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Good job!!! A few notes after checking out the code:
- Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)
- Good job using StaggeredGridView and TouchImageView for enhancing UI/UX
- Consider using Parcelable instead of Serializable ([benefits](http://stackoverflow.com/a/5551155))
- Consider adding error checks / check for internet connectivity, etc
- Great job implementing SettingsDialog for filters
- Good to see you added Search using the action bar and correctly implemented sharing 
- Good to see JSON deserializing logic in the Image object. (Consider adding null checks)

Also, here's a more detailed [Project 2 Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](https://gist.github.com/nesquena/44091e4727b154d04269) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
